---
title: "scMRD_limit_of_detection_summary"
author: "TR"
date: "2023-04-27"
output: html_document
---

```{r}

library(tidyverse)
library(pals)
library(ggplot2)
library(readxl)

```

```{r}

LOD_results<- read_xlsx("LOD_v2_results.xlsx")

LOD_results$Detection<- as.character(LOD_results$Detection)

LOD_results_names<- LOD_results %>% mutate(Patient = case_when(
                                                    .$Mutations == "NRAS_RUNX1" ~ "Patient 1",
                                                    .$Mutations == "JAK2_IDH2_DNMT3A" ~ "Patient 2",
                                                    .$Mutations == "IDH2" ~ "Patient 3"))

```

Limit of detection using a ≥ 1 cell cutoff
```{r}

gg_LOD_1_cell <- LOD_results_names %>%
                  ggplot(., aes(x=Detection, y=Cell_Number, fill = Patient)) +
                  geom_jitter(size=4, shape=21, width = 0.1,alpha = 0.8)+
                  scale_fill_manual(values = c("Patient 1" = "#332288", "Patient 2" = "#88CCEE", "Patient 3" = "#AA4499"))+
                        theme_bw()+
                  geom_hline(yintercept = 0, linetype = "dashed")+
                                  theme(axis.line.x = element_blank(),
                                      plot.title = element_text(hjust = 0.5, size = 20),
                                      axis.text.y = element_text(size=12, face = "bold"), 
                                      axis.text.x = element_text(size=12, face = "bold"), 
                                      axis.title.y = element_text(size = 14), 
                                      axis.title.x = element_text(size = 14), 
                                      legend.title = element_blank(),
                                      panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))+
                       scale_y_continuous(trans=scales::pseudo_log_trans(base = 10))+
                  ylab("Cell Number")+
                  xlab("AML Spike-in Percentage")+
                  xlim(c("0", "0.002", "0.005", "0.01", "0.1"))+
                  ggtitle("Limit of Detection (≥1 cell)")

gg_LOD_1_cell

ggsave(plot = gg_LOD_1_cell, width = 6, height = 4, dpi = 500, filename = "gg_LOD_1_cell.tiff", device = "tiff")


```

Limit of detection using a ≥ 3 cell cutoff
```{r}

gg_LOD_3_cells <- LOD_results_names %>%
                  ggplot(., aes(x=Detection, y=Cell_Number, fill = Patient)) +
                  geom_jitter(size=4, shape=21, width = 0.1,alpha = 0.8)+
                  scale_fill_manual(values = c("Patient 1" = "#332288", "Patient 2" = "#88CCEE", "Patient 3" = "#AA4499"))+
                        theme_bw()+
                  geom_hline(yintercept = 2, linetype = "dashed")+
                                  theme(axis.line.x = element_blank(),
                                      plot.title = element_text(hjust = 0.5, size = 20),
                                      axis.text.y = element_text(size=12, face = "bold"), 
                                      axis.text.x = element_text(size=12, face = "bold"), 
                                      axis.title.y = element_text(size = 14), 
                                      axis.title.x = element_text(size = 14), 
                                      legend.title = element_blank(),
                                      panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))+
                       scale_y_continuous(trans=scales::pseudo_log_trans(base = 10))+
                  ylab("Cell Number")+
                  xlab("AML Spike-in Percentage")+
                  xlim(c("0", "0.002", "0.005", "0.01", "0.1"))+
                  ggtitle("Limit of Detection (≥3 cells)")

gg_LOD_3_cells

ggsave(plot = gg_LOD_3_cells, width = 6, height = 4, dpi = 500, filename = "gg_LOD_3_cells.tiff", device = "tiff")

```







